# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  configure_virtualbox = lambda do |vb|
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
  end

  config.vm.define "master-01" do |node|
    node.vm.box = "bento/rockylinux-10"
    node.vm.box_version = "202512.01.0"
    node.vm.hostname = "master-01"
    node.vm.network "private_network", ip: "192.168.33.10"

    node.vm.provider "virtualbox" do |vb, override|
      vb.memory = 2048
      vb.cpus = 2
      configure_virtualbox.call(vb)
    end
  end

  config.vm.define "worker-01" do |node|
    node.vm.box = "bento/rockylinux-10"
    node.vm.box_version = "202512.01.0"
    node.vm.hostname = "worker-01"
    node.vm.network "private_network", ip: "192.168.33.11"

    node.vm.provider "virtualbox" do |vb, override|
      vb.memory = 8192
      vb.cpus = 4
      configure_virtualbox.call(vb)
    end

  end
end
